/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Laura
 */
public class InterfaceMapa3 extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMapa
     */
    public InterfaceMapa3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoListaMacapa = new javax.swing.JButton();
        botaoListaTeresina = new javax.swing.JButton();
        botaoListaCuritiba = new javax.swing.JButton();
        botaoListaPalmas = new javax.swing.JButton();
        botaoListaBelem = new javax.swing.JButton();
        botaoListaAracaju = new javax.swing.JButton();
        botaoListaCuiaba = new javax.swing.JButton();
        botaoListaRioJaneiro = new javax.swing.JButton();
        botaoListaRioBranco = new javax.swing.JButton();
        botaoListaCampoGrande = new javax.swing.JButton();
        botaoListaRecife = new javax.swing.JButton();
        botaoListaFortaleza = new javax.swing.JButton();
        botaoListaPortoAlegre = new javax.swing.JButton();
        botaoListaNatal = new javax.swing.JButton();
        botaoListaSaoPaulo = new javax.swing.JButton();
        botaoListaBoaVista = new javax.swing.JButton();
        botaoListaGoiania = new javax.swing.JButton();
        botaoListaSalvador = new javax.swing.JButton();
        botaoListaBrasilia = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        botaoListaVitoria = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        botaoListaFlorianopolis = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        botaoListaManaus = new javax.swing.JButton();
        botaoListaPortoVelho = new javax.swing.JButton();
        botaoMapaSaoLuis = new javax.swing.JButton();
        botaoMapaPalmas = new javax.swing.JButton();
        botaoMapaBoaVista = new javax.swing.JButton();
        botaoMapaManaus = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        botaoMapaRioBranco = new javax.swing.JButton();
        botaoMapaMacapa = new javax.swing.JButton();
        botaoMapaCuiaba = new javax.swing.JButton();
        botaoMapaBrasilia = new javax.swing.JButton();
        botaoMapaCampoGrande = new javax.swing.JButton();
        botaoMapaCuritiba = new javax.swing.JButton();
        botaoMapaBelem = new javax.swing.JButton();
        botaoMapaTeresina = new javax.swing.JButton();
        botaoMapaFortaleza = new javax.swing.JButton();
        botaoMapaNatal = new javax.swing.JButton();
        botaoMapaJoaoPessoa = new javax.swing.JButton();
        botaoMapaFlorianopolis = new javax.swing.JButton();
        botaoMapaPortoAlegre = new javax.swing.JButton();
        botaoMapaSaoPaulo = new javax.swing.JButton();
        botaoMapaBeloHorizonte = new javax.swing.JButton();
        botaoMapaVitoria = new javax.swing.JButton();
        botaoMapaSalvador = new javax.swing.JButton();
        botaoMapaAracaju = new javax.swing.JButton();
        botaoMapaMaceio = new javax.swing.JButton();
        botaoMapaRecife = new javax.swing.JButton();
        botaoMapaGoiania = new javax.swing.JButton();
        botaoMapaRioJaneiro = new javax.swing.JButton();
        botaoMapaPortoVelho = new javax.swing.JButton();
        labelMapa3 = new javax.swing.JLabel();
        campoPontuacaoF3 = new javax.swing.JTextField();
        botaoListaSaoLuis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Escolha um estado no mapa e uma alternativa com a capital correspondente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 10, 370, 20);

        jLabel3.setText("Pontuação nessa fase:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 400, 110, 14);

        botaoListaMacapa.setText("Macapá");
        botaoListaMacapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaMacapaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaMacapa);
        botaoListaMacapa.setBounds(510, 220, 80, 23);

        botaoListaTeresina.setText("Teresina");
        botaoListaTeresina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaTeresinaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaTeresina);
        botaoListaTeresina.setBounds(510, 240, 80, 23);

        botaoListaCuritiba.setText("Curitiba");
        botaoListaCuritiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaCuritibaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaCuritiba);
        botaoListaCuritiba.setBounds(430, 240, 80, 23);

        botaoListaPalmas.setText("Palmas");
        botaoListaPalmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaPalmasActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaPalmas);
        botaoListaPalmas.setBounds(430, 260, 80, 23);

        botaoListaBelem.setText("Belém");
        botaoListaBelem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaBelemActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaBelem);
        botaoListaBelem.setBounds(510, 260, 80, 23);

        botaoListaAracaju.setText("Aracaju");
        botaoListaAracaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaAracajuActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaAracaju);
        botaoListaAracaju.setBounds(430, 280, 80, 23);

        botaoListaCuiaba.setText("Cuiabá");
        botaoListaCuiaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaCuiabaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaCuiaba);
        botaoListaCuiaba.setBounds(430, 300, 80, 23);

        botaoListaRioJaneiro.setText("Rio de Janeiro");
        botaoListaRioJaneiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaRioJaneiroActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaRioJaneiro);
        botaoListaRioJaneiro.setBounds(510, 40, 80, 23);

        botaoListaRioBranco.setText("Rio Branco");
        botaoListaRioBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaRioBrancoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaRioBranco);
        botaoListaRioBranco.setBounds(430, 60, 80, 23);

        botaoListaCampoGrande.setText("Campo Grande");
        botaoListaCampoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaCampoGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaCampoGrande);
        botaoListaCampoGrande.setBounds(510, 60, 80, 23);

        botaoListaRecife.setText("Recife");
        botaoListaRecife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaRecifeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaRecife);
        botaoListaRecife.setBounds(430, 80, 80, 23);

        botaoListaFortaleza.setText("Fortaleza");
        botaoListaFortaleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaFortalezaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaFortaleza);
        botaoListaFortaleza.setBounds(510, 80, 80, 23);

        botaoListaPortoAlegre.setText("Porto Alegre");
        botaoListaPortoAlegre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaPortoAlegreActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaPortoAlegre);
        botaoListaPortoAlegre.setBounds(430, 100, 80, 23);

        botaoListaNatal.setText("Natal");
        botaoListaNatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaNatalActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaNatal);
        botaoListaNatal.setBounds(510, 100, 80, 23);

        botaoListaSaoPaulo.setText("São Paulo");
        botaoListaSaoPaulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaSaoPauloActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaSaoPaulo);
        botaoListaSaoPaulo.setBounds(430, 120, 80, 23);

        botaoListaBoaVista.setText("Boa Vista");
        botaoListaBoaVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaBoaVistaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaBoaVista);
        botaoListaBoaVista.setBounds(510, 120, 80, 23);

        botaoListaGoiania.setText("Goiania");
        botaoListaGoiania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaGoianiaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaGoiania);
        botaoListaGoiania.setBounds(430, 140, 80, 23);

        botaoListaSalvador.setText("Salvador");
        botaoListaSalvador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaSalvadorActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaSalvador);
        botaoListaSalvador.setBounds(510, 140, 80, 23);

        botaoListaBrasilia.setText("Brasília");
        botaoListaBrasilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaBrasiliaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaBrasilia);
        botaoListaBrasilia.setBounds(430, 160, 80, 23);

        jButton51.setText("Fortaleza");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(510, 160, 80, 23);

        botaoListaVitoria.setText("Vitória");
        botaoListaVitoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaVitoriaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaVitoria);
        botaoListaVitoria.setBounds(430, 180, 80, 23);

        jButton53.setText("Maceió");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton53);
        jButton53.setBounds(510, 180, 80, 23);

        botaoListaFlorianopolis.setText("Florianópolis");
        botaoListaFlorianopolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaFlorianopolisActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaFlorianopolis);
        botaoListaFlorianopolis.setBounds(430, 200, 80, 23);

        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55);
        jButton55.setBounds(510, 200, 80, 9);

        botaoListaManaus.setText("Manaus");
        botaoListaManaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaManausActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaManaus);
        botaoListaManaus.setBounds(430, 220, 80, 23);

        botaoListaPortoVelho.setText("Porto Velho");
        botaoListaPortoVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaPortoVelhoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaPortoVelho);
        botaoListaPortoVelho.setBounds(430, 40, 80, 23);
        getContentPane().add(botaoMapaSaoLuis);
        botaoMapaSaoLuis.setBounds(260, 120, 10, 10);
        getContentPane().add(botaoMapaPalmas);
        botaoMapaPalmas.setBounds(230, 150, 10, 10);
        getContentPane().add(botaoMapaBoaVista);
        botaoMapaBoaVista.setBounds(110, 50, 10, 10);

        botaoMapaManaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMapaManausActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMapaManaus);
        botaoMapaManaus.setBounds(80, 100, 10, 10);
        getContentPane().add(jButton18);
        jButton18.setBounds(80, 100, 10, 10);
        getContentPane().add(botaoMapaRioBranco);
        botaoMapaRioBranco.setBounds(40, 160, 10, 10);
        getContentPane().add(botaoMapaMacapa);
        botaoMapaMacapa.setBounds(200, 40, 10, 10);
        getContentPane().add(botaoMapaCuiaba);
        botaoMapaCuiaba.setBounds(160, 180, 10, 10);
        getContentPane().add(botaoMapaBrasilia);
        botaoMapaBrasilia.setBounds(330, 200, 10, 10);
        getContentPane().add(botaoMapaCampoGrande);
        botaoMapaCampoGrande.setBounds(170, 260, 10, 10);
        getContentPane().add(botaoMapaCuritiba);
        botaoMapaCuritiba.setBounds(200, 290, 10, 10);
        getContentPane().add(botaoMapaBelem);
        botaoMapaBelem.setBounds(190, 110, 10, 10);
        getContentPane().add(botaoMapaTeresina);
        botaoMapaTeresina.setBounds(280, 130, 10, 10);
        getContentPane().add(botaoMapaFortaleza);
        botaoMapaFortaleza.setBounds(310, 100, 10, 10);
        getContentPane().add(botaoMapaNatal);
        botaoMapaNatal.setBounds(390, 110, 10, 10);
        getContentPane().add(botaoMapaJoaoPessoa);
        botaoMapaJoaoPessoa.setBounds(370, 130, 10, 10);
        getContentPane().add(botaoMapaFlorianopolis);
        botaoMapaFlorianopolis.setBounds(280, 300, 10, 10);
        getContentPane().add(botaoMapaPortoAlegre);
        botaoMapaPortoAlegre.setBounds(180, 340, 10, 10);
        getContentPane().add(botaoMapaSaoPaulo);
        botaoMapaSaoPaulo.setBounds(230, 280, 10, 10);
        getContentPane().add(botaoMapaBeloHorizonte);
        botaoMapaBeloHorizonte.setBounds(270, 240, 10, 10);
        getContentPane().add(botaoMapaVitoria);
        botaoMapaVitoria.setBounds(370, 240, 10, 10);
        getContentPane().add(botaoMapaSalvador);
        botaoMapaSalvador.setBounds(290, 180, 10, 10);
        getContentPane().add(botaoMapaAracaju);
        botaoMapaAracaju.setBounds(380, 160, 10, 10);
        getContentPane().add(botaoMapaMaceio);
        botaoMapaMaceio.setBounds(380, 150, 10, 10);
        getContentPane().add(botaoMapaRecife);
        botaoMapaRecife.setBounds(370, 140, 10, 10);
        getContentPane().add(botaoMapaGoiania);
        botaoMapaGoiania.setBounds(210, 210, 10, 10);
        getContentPane().add(botaoMapaRioJaneiro);
        botaoMapaRioJaneiro.setBounds(360, 260, 10, 10);
        getContentPane().add(botaoMapaPortoVelho);
        botaoMapaPortoVelho.setBounds(90, 160, 10, 10);

        labelMapa3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Desktop\\Projeto PCS\\Java_Mapa_Tela_Preta-Versão-Final-Fase-3-COM-INTERFACE\\Java_Mapa_Tela_Preta (Versão Final Fase 3)\\Mapa Fase 3.jpg")); // NOI18N
        getContentPane().add(labelMapa3);
        labelMapa3.setBounds(0, -50, 460, 490);

        campoPontuacaoF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPontuacaoF3ActionPerformed(evt);
            }
        });
        getContentPane().add(campoPontuacaoF3);
        campoPontuacaoF3.setBounds(520, 390, 40, 30);

        botaoListaSaoLuis.setText("São Luís");
        botaoListaSaoLuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaSaoLuisActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListaSaoLuis);
        botaoListaSaoLuis.setBounds(510, 280, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMapaManausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMapaManausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMapaManausActionPerformed

    private void botaoListaRioJaneiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaRioJaneiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaRioJaneiroActionPerformed

    private void botaoListaRioBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaRioBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaRioBrancoActionPerformed

    private void botaoListaCampoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaCampoGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaCampoGrandeActionPerformed

    private void botaoListaRecifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaRecifeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaRecifeActionPerformed

    private void botaoListaFortalezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaFortalezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaFortalezaActionPerformed

    private void botaoListaPortoAlegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaPortoAlegreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaPortoAlegreActionPerformed

    private void botaoListaNatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaNatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaNatalActionPerformed

    private void botaoListaSaoPauloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaSaoPauloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaSaoPauloActionPerformed

    private void botaoListaBoaVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaBoaVistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaBoaVistaActionPerformed

    private void botaoListaGoianiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaGoianiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaGoianiaActionPerformed

    private void botaoListaSalvadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaSalvadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaSalvadorActionPerformed

    private void botaoListaBrasiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaBrasiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaBrasiliaActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    private void botaoListaVitoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaVitoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaVitoriaActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton53ActionPerformed

    private void botaoListaFlorianopolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaFlorianopolisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaFlorianopolisActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton55ActionPerformed

    private void botaoListaManausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaManausActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaManausActionPerformed

    private void botaoListaPortoVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaPortoVelhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaPortoVelhoActionPerformed

    private void botaoListaMacapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaMacapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaMacapaActionPerformed

    private void botaoListaTeresinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaTeresinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaTeresinaActionPerformed

    private void botaoListaCuritibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaCuritibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaCuritibaActionPerformed

    private void botaoListaPalmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaPalmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaPalmasActionPerformed

    private void botaoListaBelemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaBelemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaBelemActionPerformed

    private void botaoListaAracajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaAracajuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaAracajuActionPerformed

    private void botaoListaCuiabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaCuiabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaCuiabaActionPerformed

    private void botaoListaSaoLuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaSaoLuisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoListaSaoLuisActionPerformed

    private void campoPontuacaoF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPontuacaoF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPontuacaoF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMapa3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoListaAracaju;
    private javax.swing.JButton botaoListaBelem;
    private javax.swing.JButton botaoListaBoaVista;
    private javax.swing.JButton botaoListaBrasilia;
    private javax.swing.JButton botaoListaCampoGrande;
    private javax.swing.JButton botaoListaCuiaba;
    private javax.swing.JButton botaoListaCuritiba;
    private javax.swing.JButton botaoListaFlorianopolis;
    private javax.swing.JButton botaoListaFortaleza;
    private javax.swing.JButton botaoListaGoiania;
    private javax.swing.JButton botaoListaMacapa;
    private javax.swing.JButton botaoListaManaus;
    private javax.swing.JButton botaoListaNatal;
    private javax.swing.JButton botaoListaPalmas;
    private javax.swing.JButton botaoListaPortoAlegre;
    private javax.swing.JButton botaoListaPortoVelho;
    private javax.swing.JButton botaoListaRecife;
    private javax.swing.JButton botaoListaRioBranco;
    private javax.swing.JButton botaoListaRioJaneiro;
    private javax.swing.JButton botaoListaSalvador;
    private javax.swing.JButton botaoListaSaoLuis;
    private javax.swing.JButton botaoListaSaoPaulo;
    private javax.swing.JButton botaoListaTeresina;
    private javax.swing.JButton botaoListaVitoria;
    private javax.swing.JButton botaoMapaAracaju;
    private javax.swing.JButton botaoMapaBelem;
    private javax.swing.JButton botaoMapaBeloHorizonte;
    private javax.swing.JButton botaoMapaBoaVista;
    private javax.swing.JButton botaoMapaBrasilia;
    private javax.swing.JButton botaoMapaCampoGrande;
    private javax.swing.JButton botaoMapaCuiaba;
    private javax.swing.JButton botaoMapaCuritiba;
    private javax.swing.JButton botaoMapaFlorianopolis;
    private javax.swing.JButton botaoMapaFortaleza;
    private javax.swing.JButton botaoMapaGoiania;
    private javax.swing.JButton botaoMapaJoaoPessoa;
    private javax.swing.JButton botaoMapaMacapa;
    private javax.swing.JButton botaoMapaMaceio;
    private javax.swing.JButton botaoMapaManaus;
    private javax.swing.JButton botaoMapaNatal;
    private javax.swing.JButton botaoMapaPalmas;
    private javax.swing.JButton botaoMapaPortoAlegre;
    private javax.swing.JButton botaoMapaPortoVelho;
    private javax.swing.JButton botaoMapaRecife;
    private javax.swing.JButton botaoMapaRioBranco;
    private javax.swing.JButton botaoMapaRioJaneiro;
    private javax.swing.JButton botaoMapaSalvador;
    private javax.swing.JButton botaoMapaSaoLuis;
    private javax.swing.JButton botaoMapaSaoPaulo;
    private javax.swing.JButton botaoMapaTeresina;
    private javax.swing.JButton botaoMapaVitoria;
    private javax.swing.JTextField campoPontuacaoF3;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton55;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelMapa3;
    // End of variables declaration//GEN-END:variables
}
