/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Laura
 */
public class InterfaceMapa4 extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMapa
     */
    public InterfaceMapa4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelMapaFinal = new javax.swing.JLabel();
        campoPontuacaoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Parabéns! Você descobriu o Brasil! Sua pontuação total:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, -30, 280, 130);

        labelMapaFinal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Desktop\\Projeto PCS\\Java_Mapa_Tela_Preta-Versão-Final-Fase-3-COM-INTERFACE\\Java_Mapa_Tela_Preta (Versão Final Fase 3)\\Mapa Final.jpg")); // NOI18N
        getContentPane().add(labelMapaFinal);
        labelMapaFinal.setBounds(0, 30, 720, 640);

        campoPontuacaoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPontuacaoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(campoPontuacaoTotal);
        campoPontuacaoTotal.setBounds(310, 20, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPontuacaoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPontuacaoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPontuacaoTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMapa4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMapa4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoPontuacaoTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMapaFinal;
    // End of variables declaration//GEN-END:variables
}
